name: ModTRS
main: yetanotherx.bukkitplugin.ModTRS.ModTRS
version: 0.1
commands:
    modreq:
        description: Request help from a moderator
        usage: /<command> [message]
    modreq-check:
        description: List all the currently open requests. Use p:# to go to a page, and t:open/t:all to change the type of the request
        usage: /<command> [p:#] [t:open|all]
    modreq-info:
        description: Read a request
        usage: /<command> [id]
    modreq-claim:
        description: Claim a request
        usage: /<command> [id]
    modreq-complete:
        description: Mark a request as complete
        usage: /<command> [id]
    modreq-hold:
        description: Put request on hold
        usage: /<command> [id]
    mod-broadcast:
        description: Send a message to other moderators
        usage: /<command> [message]
    modlist:
        description: List all currently online moderators
        usage: /<command>